---
kind: pipeline
name: baseimage

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  - develop

steps:
- name: Build Docker baseimage
  image: plugins/docker
  settings:
    repo: axarev/parsr-base
    context: .
    dockerfile: docker/parsr-base/Dockerfile
    username: 
      from_secret: registry_user
    password: 
      from_secret: registry_password

---
kind: pipeline
name: API

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  - develop

steps:
- name: Change file ownership
  image: alpine:latest
  commands:
  - chown -R 1001:0 /drone/src

- name: Build API
  image: axarev/parsr-base
  environment:
    NODE_ENV: development
  commands:
  - docker/parsr/build.sh

- name: Tests
  image: axarev/parsr-base
  commands:
  - npm run test

- name: Docker tag
  image: busybox
  commands:
  - sh docker/tags.sh

- name: Build Docker API image
  image: plugins/docker
  settings:
    repo: axarev/parsr
    context: .
    dockerfile: docker/parsr/Dockerfile
    username: 
      from_secret: registry_user
    password: 
      from_secret: registry_password
    build_args:
      DEV_MODE: 'true'

depends_on:
  - baseimage

---
kind: pipeline
name: UI

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  - develop

steps:
- name: Change file ownership
  image: alpine:latest
  commands:
  - chown -R 1001:0 /drone/src

- name: Build UI
  image: registry.access.redhat.com/ubi8/nodejs-10
  environment:
    NODE_ENV: development
  commands:
  - docker/parsr-ui/build.sh
